name: Trigger Fly Export

on:
  schedule:
    - cron: '20 18 * * *'  # 20:20 in NL (UTC+2)

jobs:
  download-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Download CSV from Fly.io
        run: |
          timestamp=$(date +"%Y-%m-%dT%H-%M-%S")
          curl --fail "https://smart-isolator.fly.dev/export-unexported?token=${{ secrets.EXPORT_TOKEN }}" -o "data/batch_${timestamp}.csv"

      - name: Commit and push new CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/
          git commit -m "Add export from Fly.io on $(date -u)"
          git push
